Repository ConnectingChips/ConnectingChips-Back, pull requests merged in 2023-10, with the labels that each got.

#245 Fix/update re mind
  src/main/java/connectingchips/samchips/board/service/BoardService.java
  src/main/java/connectingchips/samchips/joinedmind/controller/JoinedMindController.java
  src/main/java/connectingchips/samchips/joinedmind/entity/JoinedMind.java
  src/main/java/connectingchips/samchips/joinedmind/service/JoinedMindService.java
  src/main/java/connectingchips/samchips/mind/dto/response/CheckReMindResponse.java
  src/main/java/connectingchips/samchips/mind/dto/response/MyMindResponse.java
  src/main/java/connectingchips/samchips/mind/service/MindService.java
Labels: 버그, 성수

#261 JSSC-119 Refactor : code review
  src/main/java/connectingchips/samchips/board/S3Uploader.java
  src/main/java/connectingchips/samchips/board/controller/BoardController.java
  src/main/java/connectingchips/samchips/board/entity/Board.java
  src/main/java/connectingchips/samchips/board/service/BoardService.java
  src/main/java/connectingchips/samchips/joinedmind/controller/JoinedMindController.java
  src/main/java/connectingchips/samchips/joinedmind/entity/JoinedMind.java
  src/main/java/connectingchips/samchips/joinedmind/repository/JoinedMindRepository.java
  src/main/java/connectingchips/samchips/joinedmind/repository/JoinedMindRepositoryImpl.java
  src/main/java/connectingchips/samchips/joinedmind/service/JoinedMindService.java
  src/main/java/connectingchips/samchips/mind/controller/MindController.java
  src/main/java/connectingchips/samchips/user/controller/UserController.java
Labels: 리팩토링, 규리

#262 JSSC-125 Fix: 프론트테스트서버 CorsConfig 추가
  src/main/java/connectingchips/samchips/security/config/SecurityConfig.java
Labels: 설정, 성수

#264 JSSC-126 Comment: addOneLineCommentToController
  src/main/java/connectingchips/samchips/board/service/BoardService.java
  src/main/java/connectingchips/samchips/joinedmind/entity/JoinedMind.java
  src/main/java/connectingchips/samchips/joinedmind/service/JoinedMindService.java
  src/main/java/connectingchips/samchips/mind/controller/MindController.java
  src/main/java/connectingchips/samchips/mind/dto/request/CreateMindRequest.java
  src/main/java/connectingchips/samchips/mind/dto/response/MyJoinedMindResponse.java
  src/main/java/connectingchips/samchips/mind/dto/response/MyMindResponse.java
  src/main/java/connectingchips/samchips/mind/service/MindService.java
  src/main/java/connectingchips/samchips/mindtype/controller/MindTypeController.java
Labels: 성수, 주석

#266 JSSC-136 Feat: Bad Exception add
  src/main/java/connectingchips/samchips/board/service/BoardService.java
Labels: 기능, 규리

#268 JSSC-145 Fix: MindError
  src/main/java/connectingchips/samchips/mind/service/MindService.java
Labels: 버그, 성수

#272 JSSC-176/refactor/S3-upload
  src/main/java/connectingchips/samchips/board/S3Uploader.java
Labels: 리팩토링, 규리

#273 JSSC-157/refactor/joinedMind-service
  src/main/java/connectingchips/samchips/joinedmind/service/JoinedMindService.java
Labels: 리팩토링, 규리

#275 JSSC-179 : Refactor s2uploader
  src/main/java/connectingchips/samchips/board/S3Uploader.java
  src/main/java/connectingchips/samchips/board/service/BoardService.java
Labels: 리팩토링, 규리

#276 JSSC-191 FEAT : Board-User-Check
  src/main/java/connectingchips/samchips/board/controller/BoardController.java
  src/main/java/connectingchips/samchips/board/service/BoardService.java
  src/main/java/connectingchips/samchips/global/exception/CommonErrorCode.java
  src/main/java/connectingchips/samchips/user/service/UserService.java
Labels: 기능, 규리

#277 Fix: board Post User Check delete
  src/main/java/connectingchips/samchips/board/controller/BoardController.java
Labels: 버그, 규리

#278 Fix: delete LoginUser Annotaion
  src/main/java/connectingchips/samchips/board/controller/BoardController.java
Labels: 버그, 규리

#280 Jssc 193 Fix : file upload fix
  src/main/java/connectingchips/samchips/board/S3Uploader.java
  src/main/java/connectingchips/samchips/board/controller/BoardController.java
  src/main/java/connectingchips/samchips/board/service/BoardService.java
Labels: 버그, 규리

#281 JSSC-192 Feat: Comment-UserCheck
  src/main/java/connectingchips/samchips/board/comment/controller/CommentController.java
  src/main/java/connectingchips/samchips/board/comment/service/CommentService.java
  src/main/java/connectingchips/samchips/board/controller/BoardController.java
  src/main/java/connectingchips/samchips/user/service/UserService.java
Labels: 기능, 규리

#284 Feat: copy build file
  .github/workflows/depoly-dev.yml
Labels: 기능, 규리

#285 Fix: ENTRYPOINT
  Dockerfile
Labels: 기능, 규리

#290 Fix: depoly-dev
  .github/workflows/depoly-dev.yml
Labels: 버그, 규리

#291 Jssc 195/feat/docker file
  .github/workflows/depoly-dev.yml
  .gitignore
Labels: 버그, 규리
