Repository ConnectingChips/ConnectingChips-Back, pull requests merged in 2023-09, with the labels that each got.

#23 Feat: 작심 관련 Entity 추가
  src/main/java/connectingchips/samchips/audit/Auditable.java
  src/main/java/connectingchips/samchips/joinedmind/entity/JoinedMind.java
  src/main/java/connectingchips/samchips/mind/entity/Mind.java
  src/main/java/connectingchips/samchips/mindtype/entity/MindType.java
Labels: 기능, 성수

#33 Feat: like entity 추가
  src/main/java/connectingchips/samchips/like/entity/Like.java
Labels: 기능, 규리

#35 Feat: comment entity add
  src/main/java/connectingchips/samchips/comment/entity/comment.java
Labels: 기능, 규리

#37 Fix/board entity
  src/main/java/connectingchips/samchips/board/entity/Board.java
Labels: 기능, 규리

#38 25 feat/ mind realted service add
  src/main/java/connectingchips/samchips/joinedmind/dto/service/JoinCheckOutPut.java
  src/main/java/connectingchips/samchips/joinedmind/entity/JoinedMind.java
  src/main/java/connectingchips/samchips/joinedmind/repository/JoinedMindRepository.java
  src/main/java/connectingchips/samchips/joinedmind/service/JoinedMindService.java
  src/main/java/connectingchips/samchips/joinedmind/service/JoinedMindServiceImpl.java
  src/main/java/connectingchips/samchips/mind/dto/service/FindMindOutput.java
  src/main/java/connectingchips/samchips/mind/entity/Mind.java
  src/main/java/connectingchips/samchips/mind/repository/MindRepository.java
  src/main/java/connectingchips/samchips/mind/service/MindService.java
  src/main/java/connectingchips/samchips/mind/service/MindServiceImpl.java
  src/main/java/connectingchips/samchips/mindtype/entity/MindType.java
  src/main/java/connectingchips/samchips/mindtype/repository/MindTypeRepository.java
  src/main/java/connectingchips/samchips/mindtype/service/MindTypeService.java
Labels: 기능, 성수

#42 Refactor: Entity update
  src/main/java/connectingchips/samchips/joinedmind/entity/JoinedMind.java
  src/main/java/connectingchips/samchips/mind/entity/Mind.java
  src/main/java/connectingchips/samchips/mindtype/entity/MindType.java
  src/main/java/connectingchips/samchips/user/domain/User.java
Labels: 리팩토링, 성수

#47 Feat: add mindcontroller & add TestDataInit
  src/main/java/connectingchips/samchips/TestDataInit.java
  src/main/java/connectingchips/samchips/joinedmind/entity/JoinedMind.java
  src/main/java/connectingchips/samchips/joinedmind/service/JoinedMindService.java
  src/main/java/connectingchips/samchips/joinedmind/service/JoinedMindServiceImpl.java
  src/main/java/connectingchips/samchips/mind/controller/MindController.java
  src/main/java/connectingchips/samchips/mind/entity/Mind.java
  src/main/java/connectingchips/samchips/mind/service/MindService.java
  src/main/java/connectingchips/samchips/mind/service/MindServiceImpl.java
  src/main/java/connectingchips/samchips/mindtype/entity/MindType.java
Labels: 기능, 성수

#50 Feat/comment create delete
  src/main/java/connectingchips/samchips/comment/controller/CommentController.java
  src/main/java/connectingchips/samchips/comment/dto/CommentRequestDto.java
  src/main/java/connectingchips/samchips/comment/dto/CommentResponseDto.java
  src/main/java/connectingchips/samchips/comment/dto/ReplyRequestDto.java
  src/main/java/connectingchips/samchips/comment/dto/ReplyResponseDto.java
  src/main/java/connectingchips/samchips/comment/entity/Comment.java
  src/main/java/connectingchips/samchips/comment/entity/Reply.java
  src/main/java/connectingchips/samchips/comment/repository/CommentRepository.java
  src/main/java/connectingchips/samchips/comment/repository/ReplyRepository.java
  src/main/java/connectingchips/samchips/comment/service/CommentService.java
  src/main/java/connectingchips/samchips/user/repository/UserRepositoryImpl.java
Labels: 기능, 규리

#51 Feat: add JoinMindController & JoinMindService
  src/main/java/connectingchips/samchips/audit/Auditable.java
  src/main/java/connectingchips/samchips/joinedmind/controller/JoinedMindController.java
  src/main/java/connectingchips/samchips/joinedmind/dto/service/JoinCheckOutPut.java
  src/main/java/connectingchips/samchips/joinedmind/entity/JoinedMind.java
  src/main/java/connectingchips/samchips/joinedmind/repository/JoinedMindRepository.java
  src/main/java/connectingchips/samchips/joinedmind/repository/JoinedMindRepositoryCustom.java
  src/main/java/connectingchips/samchips/joinedmind/repository/JoinedMindRepositoryImpl.java
  src/main/java/connectingchips/samchips/joinedmind/service/JoinedMindService.java
  src/main/java/connectingchips/samchips/mind/service/MindService.java
  src/main/java/connectingchips/samchips/mindtype/entity/MindType.java
  src/main/java/connectingchips/samchips/user/domain/User.java
Labels: 기능, 성수

#57 Feat: board basic repository 생성
  src/main/java/connectingchips/samchips/board/controller/BoardController.java
  src/main/java/connectingchips/samchips/board/dto/BoardRequestDto.java
  src/main/java/connectingchips/samchips/board/dto/BoardResponseDto.java
  src/main/java/connectingchips/samchips/board/entity/Board.java
  src/main/java/connectingchips/samchips/board/repository/BoardRepository.java
  src/main/java/connectingchips/samchips/board/service/BoardService.java
  src/main/java/connectingchips/samchips/comment/dto/CommentResponseDto.java
  src/main/java/connectingchips/samchips/comment/service/CommentService.java
Labels: 기능, 규리

#61 Feat: board delete & canEdit API
  src/main/java/connectingchips/samchips/board/controller/BoardController.java
  src/main/java/connectingchips/samchips/board/dto/BoardRequestDto.java
  src/main/java/connectingchips/samchips/board/dto/BoardResponseDto.java
  src/main/java/connectingchips/samchips/board/dto/UserEditDto.java
  src/main/java/connectingchips/samchips/board/service/BoardService.java
  src/main/java/connectingchips/samchips/comment/controller/CommentController.java
Labels: 기능, 규리

#65 Feat: board create 기능 추가
  src/main/java/connectingchips/samchips/board/controller/BoardController.java
  src/main/java/connectingchips/samchips/board/dto/BoardRequestDto.java
  src/main/java/connectingchips/samchips/board/dto/UserEditDto.java
  src/main/java/connectingchips/samchips/board/entity/Board.java
  src/main/java/connectingchips/samchips/board/service/BoardService.java
Labels: 기능, 규리

#66 Feat: board update service
  src/main/java/connectingchips/samchips/board/controller/BoardController.java
  src/main/java/connectingchips/samchips/board/dto/BoardResponseDto.java
  src/main/java/connectingchips/samchips/board/entity/Board.java
  src/main/java/connectingchips/samchips/board/service/BoardService.java
Labels: 기능, 규리

#70 Feat: add MindRelationController, and Service
  src/main/java/connectingchips/samchips/mind/controller/MindController.java
  src/main/java/connectingchips/samchips/mind/dto/service/CheckAllMindOutput.java
  src/main/java/connectingchips/samchips/mind/service/MindService.java
  src/main/java/connectingchips/samchips/mindtype/controller/MindTypeController.java
  src/main/java/connectingchips/samchips/mindtype/dto/CreateMindTypeInput.java
  src/main/java/connectingchips/samchips/mindtype/dto/MindTypeOutput.java
  src/main/java/connectingchips/samchips/mindtype/entity/MindType.java
  src/main/java/connectingchips/samchips/mindtype/service/MindTypeService.java
Labels: 기능, 성수

#82 Feat/add get join mind and minds
  src/main/java/connectingchips/samchips/board/repository/BoardRepository.java
  src/main/java/connectingchips/samchips/board/service/BoardService.java
  src/main/java/connectingchips/samchips/joinedmind/dto/service/JoinCheckOutPut.java
  src/main/java/connectingchips/samchips/joinedmind/entity/JoinedMind.java
  src/main/java/connectingchips/samchips/joinedmind/service/JoinedMindService.java
  src/main/java/connectingchips/samchips/mind/controller/MindController.java
  src/main/java/connectingchips/samchips/mind/dto/controller/CreateMindInput.java
  src/main/java/connectingchips/samchips/mind/service/MindService.java
Labels: 기능, 성수

#84 Refactor: JoinedMind
  src/main/java/connectingchips/samchips/joinedmind/controller/JoinedMindController.java
  src/main/java/connectingchips/samchips/joinedmind/dto/JoinCheckResponse.java
  src/main/java/connectingchips/samchips/joinedmind/dto/service/JoinCheckOutPut.java
  src/main/java/connectingchips/samchips/joinedmind/repository/JoinedMindRepositoryImpl.java
  src/main/java/connectingchips/samchips/joinedmind/service/JoinedMindService.java
  src/main/java/connectingchips/samchips/mind/service/MindService.java
Labels: 리팩토링, 성수

#88 Feat:board read
  src/main/java/connectingchips/samchips/board/controller/BoardController.java
  src/main/java/connectingchips/samchips/board/dto/BoardListDto.java
  src/main/java/connectingchips/samchips/board/dto/BoardResponseDto.java
  src/main/java/connectingchips/samchips/board/repository/BoardRepository.java
  src/main/java/connectingchips/samchips/board/service/BoardService.java
  src/main/java/connectingchips/samchips/comment/controller/CommentController.java
  src/main/java/connectingchips/samchips/comment/dto/CommentResponseDto.java
  src/main/java/connectingchips/samchips/comment/dto/ReplyResponseDto.java
  src/main/java/connectingchips/samchips/comment/repository/CommentRepository.java
  src/main/java/connectingchips/samchips/comment/repository/ReplyRepository.java
  src/main/java/connectingchips/samchips/comment/service/CommentService.java
Labels: 기능, 규리

#92 Feat: GetAllMindExceptMe add
  src/main/java/connectingchips/samchips/joinedmind/controller/JoinedMindController.java
  src/main/java/connectingchips/samchips/mind/controller/MindController.java
  src/main/java/connectingchips/samchips/mind/service/MindService.java
Labels: 기능, 성수

#94 Refactor: change PathVariable
  src/main/java/connectingchips/samchips/joinedmind/controller/JoinedMindController.java
  src/main/java/connectingchips/samchips/mind/controller/MindController.java
Labels: 리팩토링, 성수

#96 Feat: add-all-exception
  src/main/java/connectingchips/samchips/board/service/BoardService.java
  src/main/java/connectingchips/samchips/comment/service/CommentService.java
  src/main/java/connectingchips/samchips/exception/BadRequestException.java
  src/main/java/connectingchips/samchips/exception/ExceptionCode.java
  src/main/java/connectingchips/samchips/joinedmind/service/JoinedMindService.java
  src/main/java/connectingchips/samchips/mind/service/MindService.java
  src/main/java/connectingchips/samchips/mindtype/service/MindTypeService.java
  src/main/java/connectingchips/samchips/user/service/UserService.java
Labels: 기능, 성수

#100 Config: Security Cors Config
  src/main/java/connectingchips/samchips/user/security/config/SecurityConfig.java
Labels: 설정, 성수

#109 Refactor/check working and refactor
  src/main/java/connectingchips/samchips/board/repository/BoardRepository.java
  src/main/java/connectingchips/samchips/joinedmind/dto/JoinCheckResponse.java
  src/main/java/connectingchips/samchips/mind/controller/MindController.java
  src/main/java/connectingchips/samchips/mind/service/MindService.java
Labels: 리팩토링, 성수

#127 Fix/authentication 기능 수정
  src/main/java/connectingchips/samchips/board/controller/BoardController.java
  src/main/java/connectingchips/samchips/board/dto/BoardResponseDto.java
  src/main/java/connectingchips/samchips/board/service/BoardService.java
  src/main/java/connectingchips/samchips/comment/dto/ReplyRequestDto.java
Labels: 버그, 규리

#133 125 feat mind image entity add and add controller and service
  src/main/java/connectingchips/samchips/joinedmind/controller/JoinedMindController.java
  src/main/java/connectingchips/samchips/mind/controller/MindController.java
  src/main/java/connectingchips/samchips/mind/dto/request/CreateMindRequest.java
  src/main/java/connectingchips/samchips/mind/dto/response/FindIntroMindResponse.java
  src/main/java/connectingchips/samchips/mind/dto/response/FindPageMindResponse.java
  src/main/java/connectingchips/samchips/mind/dto/response/FindTotalMindResponse.java
  src/main/java/connectingchips/samchips/mind/dto/response/MyJoinedMindResponse.java
  src/main/java/connectingchips/samchips/mind/dto/response/MyMindResponse.java
  src/main/java/connectingchips/samchips/mind/entity/Mind.java
  src/main/java/connectingchips/samchips/mind/service/MindService.java
Labels: 기능, 성수

#134 refactor: change name and logic
  src/main/java/connectingchips/samchips/mind/controller/MindController.java
Labels: 기능, 성수

#137 Fix/delete 관련 api 수정
  src/main/java/connectingchips/samchips/board/dto/BoardResponseDto.java
  src/main/java/connectingchips/samchips/board/entity/Board.java
  src/main/java/connectingchips/samchips/comment/dto/CommentResponseDto.java
  src/main/java/connectingchips/samchips/comment/dto/ReplyRequestDto.java
  src/main/java/connectingchips/samchips/comment/dto/ReplyResponseDto.java
  src/main/java/connectingchips/samchips/comment/entity/Comment.java
  src/main/java/connectingchips/samchips/comment/service/CommentService.java
Labels: 버그, 규리

#143 Feat/ add mindService, mindController
  src/main/java/connectingchips/samchips/joinedmind/controller/JoinedMindController.java
  src/main/java/connectingchips/samchips/mind/controller/MindController.java
  src/main/java/connectingchips/samchips/mind/dto/request/CreateMindRequest.java
  src/main/java/connectingchips/samchips/mind/dto/response/IntroImageResponse.java
  src/main/java/connectingchips/samchips/mind/dto/response/PageImageResponse.java
  src/main/java/connectingchips/samchips/mind/service/MindService.java
Labels: 기능, 성수

#144 Refactor: s3 이미지 업로드 api 확인
  src/main/java/connectingchips/samchips/board/controller/BoardController.java
  src/main/java/connectingchips/samchips/board/service/BoardService.java
Labels: 리팩토링, 규리

#148 Feat: update mind entity
  src/main/java/connectingchips/samchips/mind/controller/MindController.java
  src/main/java/connectingchips/samchips/mind/entity/Mind.java
Labels: 기능, 성수

#156 Refactor: comment createAt hour and minute
  src/main/java/connectingchips/samchips/comment/dto/CommentResponseDto.java
  src/main/java/connectingchips/samchips/comment/dto/ReplyResponseDto.java
Labels: 리팩토링, 규리

#159 Feat: UUID random create
  src/main/java/connectingchips/samchips/board/S3Uploader.java
  src/main/java/connectingchips/samchips/board/service/BoardService.java
Labels: 기능, 규리

#161 fix: commentRepository -> replyRepository 변경
  src/main/java/connectingchips/samchips/comment/controller/CommentController.java
  src/main/java/connectingchips/samchips/comment/service/CommentService.java
Labels: 버그, 규리

#163 refactor: BoardRequestDto를 세부적으로 나눕니다
  src/main/java/connectingchips/samchips/board/controller/BoardController.java
  src/main/java/connectingchips/samchips/board/dto/BoardRequestDto.java
  src/main/java/connectingchips/samchips/board/service/BoardService.java
Labels: 리팩토링, 규리

#164 fix: CORS 추가
  src/main/java/connectingchips/samchips/board/controller/BoardController.java
Labels: 버그, 규리

#176 feat: FindPageMindResponse add introduce
  src/main/java/connectingchips/samchips/mind/dto/response/FindPageMindResponse.java
Labels: 기능, 성수

#178 refactor: change FindIntroMindResponse and FindPageMindResponse
  src/main/java/connectingchips/samchips/mind/dto/response/FindIntroMindResponse.java
  src/main/java/connectingchips/samchips/mind/dto/response/FindPageMindResponse.java
Labels: 리팩토링, 성수

#183 feat: file null 처리
  src/main/java/connectingchips/samchips/board/service/BoardService.java
Labels: 기능, 규리

#187 Refactor/change response
  src/main/java/connectingchips/samchips/board/service/BoardService.java
  src/main/java/connectingchips/samchips/joinedmind/entity/JoinedMind.java
  src/test/java/connectingchips/samchips/mindtype/MindTypeSubData.java
  src/test/java/connectingchips/samchips/mindtype/service/MindTypeServiceTest.java
Labels: 기능, 성수

#190 Feat: add checkKeepJoin
  src/main/java/connectingchips/samchips/mind/controller/MindController.java
  src/main/java/connectingchips/samchips/mind/dto/response/CheckReMindResponse.java
  src/main/java/connectingchips/samchips/mind/service/MindService.java
Labels: 기능, 성수

#216 fix: private -> public method
  src/main/java/connectingchips/samchips/board/controller/BoardController.java
  src/main/java/connectingchips/samchips/comment/controller/CommentController.java
Labels: 버그, 규리

#223 Fix: findAllMindExceptMeBy
  src/main/java/connectingchips/samchips/mind/service/MindService.java
Labels: 버그, 성수

#225 Feat: 글자수 제한 어노테이션 추가
  src/main/java/connectingchips/samchips/board/entity/Board.java
  src/main/java/connectingchips/samchips/comment/entity/Comment.java
  src/main/java/connectingchips/samchips/comment/entity/Reply.java
Labels: 기능, 규리

#229 Feat/board count add reply and board data reverse
  src/main/java/connectingchips/samchips/board/service/BoardService.java
Labels: 기능, 성수

#232 feat: 이미지 확장자 제한 및 리팩토링
  src/main/java/connectingchips/samchips/board/S3Uploader.java
  src/main/java/connectingchips/samchips/exception/CommonErrorCode.java
Labels: 기능, 규리

#235 Refactor: 스케쥴러 시간 변경
  src/main/java/connectingchips/samchips/joinedmind/repository/JoinedMindRepositoryImpl.java
Labels: 리팩토링, 규리
